name: rocket_workshop_auth
description: Rocket Workshop 通用认证 SDK
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.8.0
  crypto: ^3.0.3
  http: ^1.6.0
  path: ^1.8.3
  xml: ^6.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
